cutadapt -g CCAACATCGAGGTCRYAA -o BS1I.trimF.fastq BS1I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o BS1I.trimFR.fastq BS1I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o CT4I.trimF.fastq CT4I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o CT4I.trimFR.fastq CT4I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o CT5I.trimF.fastq CT5I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o CT5I.trimFR.fastq CT5I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o EJ26I.trimF.fastq EJ26I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o EJ26I.trimFR.fastq EJ26I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o EJ34I.trimF.fastq EJ34I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o EJ34I.trimFR.fastq EJ34I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o FA1I.trimF.fastq FA1I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o FA1I.trimFR.fastq FA1I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o FA2I.trimF.fastq FA2I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o FA2I.trimFR.fastq FA2I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o FP4I.trimF.fastq FP4I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o FP4I.trimFR.fastq FP4I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o FP15I.trimF.fastq FP15I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o FP15I.trimFR.fastq FP15I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o HP1I.trimF.fastq HP1I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o HP1I.trimFR.fastq HP1I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o HS6I.trimF.fastq HS6I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o HS6I.trimFR.fastq HS6I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o HS7I.trimF.fastq HS7I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o HS7I.trimFR.fastq HS7I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o HS8I.trimF.fastq HS8I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o HS8I.trimFR.fastq HS8I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o INC_APR22.trimF.fastq INC_APR22.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o INC_APR22.trimFR.fastq INC_APR22.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o INC_JUN1.trimF.fastq INC_JUN1.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o INC_JUN1.trimFR.fastq INC_JUN1.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o IPC.trimF.fastq IPC.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o IPC.trimFR.fastq IPC.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o M151I.trimF.fastq M151I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o M151I.trimFR.fastq M151I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o M232I.trimF.fastq M232I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o M232I.trimFR.fastq M232I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o M241I.trimF.fastq M241I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o M241I.trimFR.fastq M241I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o M350I.trimF.fastq M350I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o M350I.trimFR.fastq M350I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o NYBG8I.trimF.fastq NYBG8I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o NYBG8I.trimFR.fastq NYBG8I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o NYBG9I.trimF.fastq NYBG9I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o NYBG9I.trimFR.fastq NYBG9I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PBP15I.trimF.fastq PBP15I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PBP15I.trimFR.fastq PBP15I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PBP19I.trimF.fastq PBP19I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PBP19I.trimFR.fastq PBP19I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PBP41I.trimF.fastq PBP41I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PBP41I.trimFR.fastq PBP41I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PBP42I.trimF.fastq PBP42I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PBP42I.trimFR.fastq PBP42I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PC8I.trimF.fastq PC8I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PC8I.trimFR.fastq PC8I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PP1I.trimF.fastq PP1I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PP1I.trimFR.fastq PP1I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PP3I.trimF.fastq PP3I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PP3I.trimFR.fastq PP3I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PP5I.trimF.fastq PP5I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PP5I.trimFR.fastq PP5I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PP7I.trimF.fastq PP7I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PP7I.trimFR.fastq PP7I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o PP9I.trimF.fastq PP9I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o PP9I.trimFR.fastq PP9I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD2I.trimF.fastq RD2I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD2I.trimFR.fastq RD2I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD4I.trimF.fastq RD4I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD4I.trimFR.fastq RD4I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD5I.trimF.fastq RD5I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD5I.trimFR.fastq RD5I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD10I.trimF.fastq RD10I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD10I.trimFR.fastq RD10I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD11I.trimF.fastq RD11I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD11I.trimFR.fastq RD11I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD12I.trimF.fastq RD12I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD12I.trimFR.fastq RD12I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD18I.trimF.fastq RD18I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD18I.trimFR.fastq RD18I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD23I.trimF.fastq RD23I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD23I.trimFR.fastq RD23I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD25I.trimF.fastq RD25I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD25I.trimFR.fastq RD25I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RD26I.trimF.fastq RD26I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RD26I.trimFR.fastq RD26I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RRP3I.trimF.fastq RRP3I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RRP3I.trimFR.fastq RRP3I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o RRP6I.trimF.fastq RRP6I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o RRP6I.trimFR.fastq RRP6I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o SR11I.trimF.fastq SR11I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o SR11I.trimFR.fastq SR11I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o SR19I.trimF.fastq SR19I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o SR19I.trimFR.fastq SR19I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o SR29I.trimF.fastq SR29I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o SR29I.trimFR.fastq SR29I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o ST3I.trimF.fastq ST3I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o ST3I.trimFR.fastq ST3I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o ST4I.trimF.fastq ST4I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o ST4I.trimFR.fastq ST4I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o ST5I.trimF.fastq ST5I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o ST5I.trimFR.fastq ST5I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o SV5I.trimF.fastq SV5I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o SV5I.trimFR.fastq SV5I.trimF.fastq
cutadapt -g CCAACATCGAGGTCRYAA -o VC23I.trimF.fastq VC23I.fastq
cutadapt -a CTGTTATCCCTANRGTAAYT -o VC23I.trimFR.fastq VC23I.trimF.fastq