obiannotate -S 'sample:BP3I' Inverts/BP3I.trimFR.fastq > InvertsAnn/BP3I.ann.fastq
obiannotate -S 'sample:BS1I' Inverts/BS1I.trimFR.fastq > InvertsAnn/BS1I.ann.fastq
obiannotate -S 'sample:CT4I' Inverts/CT4I.trimFR.fastq > InvertsAnn/CT4I.ann.fastq
obiannotate -S 'sample:CT5I' Inverts/CT5I.trimFR.fastq > InvertsAnn/CT5I.ann.fastq
obiannotate -S 'sample:EJ26I' Inverts/EJ26I.trimFR.fastq > InvertsAnn/EJ26I.ann.fastq
obiannotate -S 'sample:EJ34I' Inverts/EJ34I.trimFR.fastq > InvertsAnn/EJ34I.ann.fastq
obiannotate -S 'sample:FA1I' Inverts/FA1I.trimFR.fastq > InvertsAnn/FA1I.ann.fastq
obiannotate -S 'sample:FA2I' Inverts/FA2I.trimFR.fastq > InvertsAnn/FA2I.ann.fastq
obiannotate -S 'sample:FP4I' Inverts/FP4I.trimFR.fastq > InvertsAnn/FP4I.ann.fastq
obiannotate -S 'sample:FP15I' Inverts/FP15I.trimFR.fastq > InvertsAnn/FP15I.ann.fastq
obiannotate -S 'sample:HP1I' Inverts/HP1I.trimFR.fastq > InvertsAnn/HP1I.ann.fastq
obiannotate -S 'sample:HS6I' Inverts/HS6I.trimFR.fastq > InvertsAnn/HS6I.ann.fastq
obiannotate -S 'sample:HS7I' Inverts/HS7I.trimFR.fastq > InvertsAnn/HS7I.ann.fastq
obiannotate -S 'sample:HS8I' Inverts/HS8I.trimFR.fastq > InvertsAnn/HS8I.ann.fastq
obiannotate -S 'sample:INC_APR22' Inverts/INC_APR22.trimFR.fastq > InvertsAnn/INC_APR22.ann.fastq
obiannotate -S 'sample:INC_JUN1' Inverts/INC_JUN1.trimFR.fastq > InvertsAnn/INC_JUN1.ann.fastq
obiannotate -S 'sample:IPC' Inverts/IPC.trimFR.fastq > InvertsAnn/IPC.ann.fastq
obiannotate -S 'sample:M151I' Inverts/M151I.trimFR.fastq > InvertsAnn/M151I.ann.fastq
obiannotate -S 'sample:M232I' Inverts/M232I.trimFR.fastq > InvertsAnn/M232I.ann.fastq
obiannotate -S 'sample:M241I' Inverts/M241I.trimFR.fastq > InvertsAnn/M241I.ann.fastq
obiannotate -S 'sample:M350I' Inverts/M350I.trimFR.fastq > InvertsAnn/M350I.ann.fastq
obiannotate -S 'sample:NYBG8I' Inverts/NYBG8I.trimFR.fastq > InvertsAnn/NYBG8I.ann.fastq
obiannotate -S 'sample:NYBG9I' Inverts/NYBG9I.trimFR.fastq > InvertsAnn/NYBG9I.ann.fastq
obiannotate -S 'sample:PBP15I' Inverts/PBP15I.trimFR.fastq > InvertsAnn/PBP15I.ann.fastq
obiannotate -S 'sample:PBP19I' Inverts/PBP19I.trimFR.fastq > InvertsAnn/PBP19I.ann.fastq
obiannotate -S 'sample:PBP41I' Inverts/PBP41I.trimFR.fastq > InvertsAnn/PBP41I.ann.fastq
obiannotate -S 'sample:PBP42I' Inverts/PBP42I.trimFR.fastq > InvertsAnn/PBP42I.ann.fastq
obiannotate -S 'sample:PC8I' Inverts/PC8I.trimFR.fastq > InvertsAnn/PC8I.ann.fastq
obiannotate -S 'sample:PP1I' Inverts/PP1I.trimFR.fastq > InvertsAnn/PP1I.ann.fastq
obiannotate -S 'sample:PP3I' Inverts/PP3I.trimFR.fastq > InvertsAnn/PP3I.ann.fastq
obiannotate -S 'sample:PP5I' Inverts/PP5I.trimFR.fastq > InvertsAnn/PP5I.ann.fastq
obiannotate -S 'sample:PP7I' Inverts/PP7I.trimFR.fastq > InvertsAnn/PP7I.ann.fastq
obiannotate -S 'sample:PP8I' Inverts/PP8I.trimFR.fastq > InvertsAnn/PP8I.ann.fastq
obiannotate -S 'sample:PP9I' Inverts/PP9I.trimFR.fastq > InvertsAnn/PP9I.ann.fastq
obiannotate -S 'sample:RD2I' Inverts/RD2I.trimFR.fastq > InvertsAnn/RD2I.ann.fastq
obiannotate -S 'sample:RD4I' Inverts/RD4I.trimFR.fastq > InvertsAnn/RD4I.ann.fastq
obiannotate -S 'sample:RD5I' Inverts/RD5I.trimFR.fastq > InvertsAnn/RD5I.ann.fastq
obiannotate -S 'sample:RD10I' Inverts/RD10I.trimFR.fastq > InvertsAnn/RD10I.ann.fastq
obiannotate -S 'sample:RD11I' Inverts/RD11I.trimFR.fastq > InvertsAnn/RD11I.ann.fastq
obiannotate -S 'sample:RD12I' Inverts/RD12I.trimFR.fastq > InvertsAnn/RD12I.ann.fastq
obiannotate -S 'sample:RD18I' Inverts/RD18I.trimFR.fastq > InvertsAnn/RD18I.ann.fastq
obiannotate -S 'sample:RD23I' Inverts/RD23I.trimFR.fastq > InvertsAnn/RD23I.ann.fastq
obiannotate -S 'sample:RD25I' Inverts/RD25I.trimFR.fastq > InvertsAnn/RD25I.ann.fastq
obiannotate -S 'sample:RD26I' Inverts/RD26I.trimFR.fastq > InvertsAnn/RD26I.ann.fastq
obiannotate -S 'sample:RRP3I' Inverts/RRP3I.trimFR.fastq > InvertsAnn/RRP3I.ann.fastq
obiannotate -S 'sample:RRP6I' Inverts/RRP6I.trimFR.fastq > InvertsAnn/RRP6I.ann.fastq
obiannotate -S 'sample:SR11I' Inverts/SR11I.trimFR.fastq > InvertsAnn/SR11I.ann.fastq
obiannotate -S 'sample:SR19I' Inverts/SR19I.trimFR.fastq > InvertsAnn/SR19I.ann.fastq
obiannotate -S 'sample:SR29I' Inverts/SR29I.trimFR.fastq > InvertsAnn/SR29I.ann.fastq
obiannotate -S 'sample:ST3I' Inverts/ST3I.trimFR.fastq > InvertsAnn/ST3I.ann.fastq
obiannotate -S 'sample:ST4I' Inverts/ST4I.trimFR.fastq > InvertsAnn/ST4I.ann.fastq
obiannotate -S 'sample:ST5I' Inverts/ST5I.trimFR.fastq > InvertsAnn/ST5I.ann.fastq
obiannotate -S 'sample:SV5I' Inverts/SV5I.trimFR.fastq > InvertsAnn/SV5I.ann.fastq
obiannotate -S 'sample:VC23I' Inverts/VC23I.trimFR.fastq > InvertsAnn/VC23I.ann.fastq