cutadapt -g GGGCAATCCTGAGCCAA -o BP3PL.trimF.fastq BP3PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o BP3PL.trimFR.fastq BP3PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o BS1PL.trimF.fastq BS1PL2.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o BS1PL.trimFR.fastq BS1PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o CN2PL.trimF.fastq CN2PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o CN2PL.trimFR.fastq CN2PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o CT4PL.trimF.fastq CT4PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o CT4PL.trimFR.fastq CT4PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o CT5PL-PP8I.trimF.fastq CT5PL-PP8I.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o CT5PL-PP8I.trimFR.fastq CT5PL-PP8I.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o EJ2PL.trimF.fastq EJ2PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o EJ2PL.trimFR.fastq EJ2PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o EJ26PL.trimF.fastq EJ26PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o EJ26PL.trimFR.fastq EJ26PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o EJ28PL.trimF.fastq EJ28PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o EJ28PL.trimFR.fastq EJ28PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o EJ32PL.trimF.fastq EJ32PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o EJ32PL.trimFR.fastq EJ32PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o EJ34PL.trimF.fastq EJ34PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o EJ34PL.trimFR.fastq EJ34PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o EJ40PL.trimF.fastq EJ40PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o EJ40PL.trimFR.fastq EJ40PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o FA1PL.trimF.fastq FA1PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o FA1PL.trimFR.fastq FA1PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o FA2PL.trimF.fastq FA2PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o FA2PL.trimFR.fastq FA2PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o FP4PL.trimF.fastq FP4PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o FP4PL.trimFR.fastq FP4PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o FP15PL.trimF.fastq FP15PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o FP15PL.trimFR.fastq FP15PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o HP1PL.trimF.fastq HP1PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o HP1PL.trimFR.fastq HP1PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o HS6PL.trimF.fastq HS6PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o HS6PL.trimFR.fastq HS6PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o HS7PL.trimF.fastq HS7PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o HS7PL.trimFR.fastq HS7PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o HS8PL.trimF.fastq HS8PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o HS8PL.trimFR.fastq HS8PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o M151PL.trimF.fastq M151PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o M151PL.trimFR.fastq M151PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o M174PL.trimF.fastq M174PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o M174PL.trimFR.fastq M174PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o M221PL.trimF.fastq M221PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o M221PL.trimFR.fastq M221PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o M232PL.trimF.fastq M232PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o M232PL.trimFR.fastq M232PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o M239PL.trimF.fastq M239PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o M239PL.trimFR.fastq M239PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o M241PL.trimF.fastq M241PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o M241PL.trimFR.fastq M241PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o M251PL.trimF.fastq M251PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o M251PL.trimFR.fastq M251PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o M350PL.trimF.fastq M350PL2.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o M350PL.trimFR.fastq M350PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o NYBG8PL.trimF.fastq NYBG8PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o NYBG8PL.trimFR.fastq NYBG8PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o NYBG9PL.trimF.fastq NYBG9PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o NYBG9PL.trimFR.fastq NYBG9PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o NYBG10PL.trimF.fastq NYBG10PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o NYBG10PL.trimFR.fastq NYBG10PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PBP15PL.trimF.fastq PBP15PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PBP15PL.trimFR.fastq PBP15PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PBP41PL.trimF.fastq PBP41PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PBP41PL.trimFR.fastq PBP41PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PBP42PL.trimF.fastq PBP42PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PBP42PL.trimFR.fastq PBP42PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PC8PL.trimF.fastq PC8PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PC8PL.trimFR.fastq PC8PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PLNC_APR22.trimF.fastq PLNC-APR22.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PLNC_APR22.trimFR.fastq PLNC_APR22.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PLNC_JUN1.trimF.fastq PLNC-JUN1.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PLNC_JUN1.trimFR.fastq PLNC_JUN1.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PLNC_JUN3.trimF.fastq PLNC-JUN3.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PLNC_JUN3.trimFR.fastq PLNC_JUN3.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PLNC_JUN6.trimF.fastq PLNC-JUN6.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PLNC_JUN6.trimFR.fastq PLNC_JUN6.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PLNC_JUN9.trimF.fastq PLNC-JUN9.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PLNC_JUN9.trimFR.fastq PLNC_JUN9.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PLPC.trimF.fastq PLPC.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PLPC.trimFR.fastq PLPC.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PLPOS.trimF.fastq PLPOS.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PLPOS.trimFR.fastq PLPOS.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PP1PL.trimF.fastq PP1PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PP1PL.trimFR.fastq PP1PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PP3PL.trimF.fastq PP3PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PP3PL.trimFR.fastq PP3PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PP5PL.trimF.fastq PP5PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PP5PL.trimFR.fastq PP5PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PP7PL.trimF.fastq PP7PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PP7PL.trimFR.fastq PP7PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PP8PL.trimF.fastq PP8PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PP8PL.trimFR.fastq PP8PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o PP9PL.trimF.fastq PP9PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o PP9PL.trimFR.fastq PP9PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD2PL.trimF.fastq RD2PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD2PL.trimFR.fastq RD2PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD4PL.trimF.fastq RD4PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD4PL.trimFR.fastq RD4PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD5PL.trimF.fastq RD5PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD5PL.trimFR.fastq RD5PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD10PL.trimF.fastq RD10PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD10PL.trimFR.fastq RD10PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD11PL.trimF.fastq RD11PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD11PL.trimFR.fastq RD11PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD12PL.trimF.fastq RD12PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD12PL.trimFR.fastq RD12PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD14PL.trimF.fastq RD14PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD14PL.trimFR.fastq RD14PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD15PL.trimF.fastq RD15PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD15PL.trimFR.fastq RD15PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD18PL.trimF.fastq RD18PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD18PL.trimFR.fastq RD18PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD23PL.trimF.fastq RD23PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD23PL.trimFR.fastq RD23PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD25PL.trimF.fastq RD25PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD25PL.trimFR.fastq RD25PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RD26PL.trimF.fastq RD26PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RD26PL.trimFR.fastq RD26PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RRP3PL.trimF.fastq RRP3PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RRP3PL.trimFR.fastq RRP3PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RRP4BPL.trimF.fastq RRP4BPL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RRP4BPL.trimFR.fastq RRP4BPL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RRP4PL.trimF.fastq RRP4PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RRP4PL.trimFR.fastq RRP4PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RRP5PL.trimF.fastq RRP5PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RRP5PL.trimFR.fastq RRP5PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o RRP6PL.trimF.fastq RRP6PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o RRP6PL.trimFR.fastq RRP6PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o SR11PL.trimF.fastq SR11PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o SR11PL.trimFR.fastq SR11PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o SR19PL.trimF.fastq SR19PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o SR19PL.trimFR.fastq SR19PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o SR24PL.trimF.fastq SR24PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o SR24PL.trimFR.fastq SR24PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o SR29PL.trimF.fastq SR29PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o SR29PL.trimFR.fastq SR29PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o ST3PL.trimF.fastq ST3PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o ST3PL.trimFR.fastq ST3PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o ST4PL.trimF.fastq ST4PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o ST4PL.trimFR.fastq ST4PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o ST5PL.trimF.fastq ST5PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o ST5PL.trimFR.fastq ST5PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o SV5PL.trimF.fastq SV5PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o SV5PL.trimFR.fastq SV5PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o VC12PL.trimF.fastq VC12PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o VC12PL.trimFR.fastq VC12PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o VC23PL.trimF.fastq VC23PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o VC23PL.trimFR.fastq VC23PL.trimF.fastq
cutadapt -g GGGCAATCCTGAGCCAA -o VC34PL.trimF.fastq VC34PL.fastq
cutadapt -a GATAGGTGCAGAGACTCAATGG -o VC384PL.trimFR.fastq VC34PL.trimF.fastq