obiannotate -S 'sample:BP3PL' Plants/BP3PL.trimFR.fastq > PlantsAnn/BP3PL.ann.fastq
obiannotate -S 'sample:BS1PL' Plants/BS1PL.trimFR.fastq > PlantsAnn/BS1PL.ann.fastq
obiannotate -S 'sample:CN2PL' Plants/CN2PL.trimFR.fastq > PlantsAnn/CN2PL.ann.fastq
obiannotate -S 'sample:CT4PL' Plants/CT4PL.trimFR.fastq > PlantsAnn/CT4PL.ann.fastq
obiannotate -S 'sample:CT5PL-PP8I' Plants/CT5PL-PP8I.trimFR.fastq > PlantsAnn/CT5PL-PP8I.ann.fastq
obiannotate -S 'sample:EJ2PL' Plants/EJ2PL.trimFR.fastq > PlantsAnn/EJ2PL.ann.fastq
obiannotate -S 'sample:EJ26PL' Plants/EJ26PL.trimFR.fastq > PlantsAnn/EJ26PL.ann.fastq
obiannotate -S 'sample:EJ28PL' Plants/EJ28PL.trimFR.fastq > PlantsAnn/EJ28PL.ann.fastq
obiannotate -S 'sample:EJ32PL' Plants/EJ32PL.trimFR.fastq > PlantsAnn/EJ32PL.ann.fastq
obiannotate -S 'sample:EJ34PL' Plants/EJ34PL.trimFR.fastq > PlantsAnn/EJ34PL.ann.fastq
obiannotate -S 'sample:EJ40PL' Plants/EJ40PL.trimFR.fastq > PlantsAnn/EJ40PL.ann.fastq
obiannotate -S 'sample:FA1PL' Plants/FA1PL.trimFR.fastq > PlantsAnn/FA1PL.ann.fastq
obiannotate -S 'sample:FA2PL' Plants/FA2PL.trimFR.fastq > PlantsAnn/FA2PL.ann.fastq
obiannotate -S 'sample:FP4PL' Plants/FP4PL.trimFR.fastq > PlantsAnn/FP4PL.ann.fastq
obiannotate -S 'sample:FP15PL' Plants/FP15PL.trimFR.fastq > PlantsAnn/FP15PL.ann.fastq
obiannotate -S 'sample:HP1PL' Plants/HP1PL.trimFR.fastq > PlantsAnn/HP1PL.ann.fastq
obiannotate -S 'sample:HS6PL' Plants/HS6PL.trimFR.fastq > PlantsAnn/HS6PL.ann.fastq
obiannotate -S 'sample:HS7PL' Plants/HS7PL.trimFR.fastq > PlantsAnn/HS7PL.ann.fastq
obiannotate -S 'sample:HS8PL' Plants/HS8PL.trimFR.fastq > PlantsAnn/HS8PL.ann.fastq
obiannotate -S 'sample:M151PL' Plants/M151PL.trimFR.fastq > PlantsAnn/M151PL.ann.fastq
obiannotate -S 'sample:M174PL' Plants/M174PL.trimFR.fastq > PlantsAnn/M174PL.ann.fastq
obiannotate -S 'sample:M221PL' Plants/M221PL.trimFR.fastq > PlantsAnn/M221PL.ann.fastq
obiannotate -S 'sample:M232PL' Plants/M232PL.trimFR.fastq > PlantsAnn/M232PL.ann.fastq
obiannotate -S 'sample:M239PL' Plants/M239PL.trimFR.fastq > PlantsAnn/M239PL.ann.fastq
obiannotate -S 'sample:M241PL' Plants/M241PL.trimFR.fastq > PlantsAnn/M241PL.ann.fastq
obiannotate -S 'sample:M251PL' Plants/M251PL.trimFR.fastq > PlantsAnn/M251PL.ann.fastq
obiannotate -S 'sample:M350PL' Plants/M350PL.trimFR.fastq > PlantsAnn/M350PL.ann.fastq
obiannotate -S 'sample:NYBG8PL' Plants/NYBG8PL.trimFR.fastq > PlantsAnn/NYBG8PL.ann.fastq
obiannotate -S 'sample:NYBG9PL' Plants/NYBG9PL.trimFR.fastq > PlantsAnn/NYBG9PL.ann.fastq
obiannotate -S 'sample:NYBG10PL' Plants/NYBG10PL.trimFR.fastq > PlantsAnn/NYBG10PL.ann.fastq
obiannotate -S 'sample:PBP15PL' Plants/PBP15PL.trimFR.fastq > PlantsAnn/PBP15PL.ann.fastq
obiannotate -S 'sample:PBP41PL' Plants/PBP41PL.trimFR.fastq > PlantsAnn/PBP41PL.ann.fastq
obiannotate -S 'sample:PBP42PL' Plants/PBP42PL.trimFR.fastq > PlantsAnn/PBP42PL.ann.fastq
obiannotate -S 'sample:PC8PL' Plants/PC8PL.trimFR.fastq > PlantsAnn/PC8PL.ann.fastq
obiannotate -S 'sample:PLNC_APR22' Plants/PLNC_APR22.trimFR.fastq > PlantsAnn/PLNC_APR22.ann.fastq
obiannotate -S 'sample:PLNC_JUN1' Plants/PLNC_JUN1.trimFR.fastq > PlantsAnn/PLNC_JUN1.ann.fastq
obiannotate -S 'sample:PLNC_JUN3' Plants/PLNC_JUN3.trimFr.fastq > PlantsAnn/PLNC_JUN3.ann.fastq
obiannotate -S 'sample:PLNC-JUN6PL' Plants/PLNC_JUN6.trimFR.fastq > PlantsAnn/PLNC_JUN6.ann.fastq
obiannotate -S 'sample:PLNC-JUN9PL' Plants/PLNC_JUN9.trimFR.fastq > PlantsAnn/PLNC_JUN9.ann.fastq
obiannotate -S 'sample:PLPC' Plants/PLPC.trimFR.fastq > PlantsAnn/PLPC.ann.fastq
obiannotate -S 'sample:PLPOS' Plants/PLPOS.trimFR.fastq > PlantsAnn/PLPOS.ann.fastq
obiannotate -S 'sample:PP1PL' Plants/PP1PL.trimFR.fastq > PlantsAnn/PP1PL.ann.fastq
obiannotate -S 'sample:PP3PL' Plants/PP3PL.trimFR.fastq > PlantsAnn/PP3PL.ann.fastq
obiannotate -S 'sample:PP5PL' Plants/PP5PL.trimFR.fastq > PlantsAnn/PP5PL.ann.fastq
obiannotate -S 'sample:PP7PL' Plants/PP7PL.trimFR.fastq > PlantsAnn/PP7PL.ann.fastq
obiannotate -S 'sample:PP8PL' Plants/PP8PL.trimFR.fastq > PlantsAnn/PP8PL.ann.fastq
obiannotate -S 'sample:PP9PL' Plants/PP9PL.trimFR.fastq > PlantsAnn/PP9PL.ann.fastq
obiannotate -S 'sample:RD2PL' Plants/RD2PL.trimFR.fastq > PlantsAnn/RD2PL.ann.fastq
obiannotate -S 'sample:RD5PL' Plants/RD5PL.trimFR.fastq > PlantsAnn/RD5PL.ann.fastq
obiannotate -S 'sample:RD10PL' Plants/RD10PL.trimFR.fastq > PlantsAnn/RD10PL.ann.fastq
obiannotate -S 'sample:RD11PL' Plants/RD11PL.trimFR.fastq > PlantsAnn/RD11PL.ann.fastq
obiannotate -S 'sample:RD12PL' Plants/RD12PL.trimFR.fastq > PlantsAnn/RD12PL.ann.fastq
obiannotate -S 'sample:RD14PL' Plants/RD14PL.trimFR.fastq > PlantsAnn/RD14PL.ann.fastq
obiannotate -S 'sample:RD15PL' Plants/RD15PL.trimFR.fastq > PlantsAnn/RD15PL.ann.fastq
obiannotate -S 'sample:RD18PL' Plants/RD18PL.trimFR.fastq > PlantsAnn/RD18PL.ann.fastq
obiannotate -S 'sample:RD23PL' Plants/RD23PL.trimFR.fastq > PlantsAnn/RD23PL.ann.fastq
obiannotate -S 'sample:RD25PL' Plants/RD25PL.trimFR.fastq > PlantsAnn/RD25PL.ann.fastq
obiannotate -S 'sample:RD26PL' Plants/RD26PL.trimFR.fastq > PlantsAnn/RD26PL.ann.fastq
obiannotate -S 'sample:RRP3PL' Plants/RRP3PL.trimFR.fastq > PlantsAnn/RRP3PL.ann.fastq
obiannotate -S 'sample:RRP4BPL' Plants/RRP4BPL.trimFR.fastq > PlantsAnn/RRP4BPL.ann.fastq
obiannotate -S 'sample:RRP4PL' Plants/RRP4PL.trimFR.fastq > PlantsAnn/RRP4PL.ann.fastq
obiannotate -S 'sample:RRP5PL' Plants/RRP5PL.trimFR.fastq > PlantsAnn/RRP5PL.ann.fastq
obiannotate -S 'sample:RRP6PL' Plants/RRP6PL.trimFR.fastq > PlantsAnn/RRP6PL.ann.fastq
obiannotate -S 'sample:SR11PL' Plants/SR11PL.trimFR.fastq > PlantsAnn/SR11PL.ann.fastq
obiannotate -S 'sample:SR19PL' Plants/SR19PL.trimFR.fastq > PlantsAnn/SR19PL.ann.fastq
obiannotate -S 'sample:SR24PL' Plants/SR24PL.trimFR.fastq > PlantsAnn/SR24PL.ann.fastq
obiannotate -S 'sample:SR29PL' Plants/SR29PL.trimFR.fastq > PlantsAnn/SR29PL.ann.fastq
obiannotate -S 'sample:ST3PL' Plants/ST3PL.trimFR.fastq > PlantsAnn/ST3PL.ann.fastq
obiannotate -S 'sample:ST4PL' Plants/ST4PL.trimFR.fastq > PlantsAnn/ST4PL.ann.fastq
obiannotate -S 'sample:ST5PL' Plants/ST5PL.trimFR.fastq > PlantsAnn/ST5PL.ann.fastq
obiannotate -S 'sample:SV5PL' Plants/SV5PL.trimFR.fastq > PlantsAnn/SV5PL.ann.fastq
obiannotate -S 'sample:VC12PL' Plants/VC12PL.trimFR.fastq > PlantsAnn/VC12PL.ann.fastq
obiannotate -S 'sample:VC23PL' Plants/VC23PL.trimFR.fastq > PlantsAnn/VC23PL.ann.fastq
obiannotate -S 'sample:VC34PL' Plants/VC34PL.trimFR.fastq > PlantsAnn/VC34PL.ann.fastq