obiannotate -S 'sample:bp3v' vertCat/bp3v.fastq > vertCatAnn/bp3v.ann.fastq
obiannotate -S 'sample:bp6v' vertCat/bp6v.fastq > vertCatAnn/bp6v.ann.fastq
obiannotate -S 'sample:cn1v' vertCat/cn1v.fastq > vertCatAnn/cn1v.ann.fastq
obiannotate -S 'sample:cn2v' vertCat/cn2v.fastq > vertCatAnn/cn2v.ann.fastq
obiannotate -S 'sample:ct1v' vertCat/ct1v.fastq > vertCatAnn/ct1v.ann.fastq
obiannotate -S 'sample:ct2v' vertCat/ct2v.fastq > vertCatAnn/ct2v.ann.fastq
obiannotate -S 'sample:ct3v' vertCat/ct3v.fastq > vertCatAnn/ct3v.ann.fastq
obiannotate -S 'sample:ej1v' vertCat/ej1v.fastq > vertCatAnn/ej1v.ann.fastq
obiannotate -S 'sample:ej2v' vertCat/ej2v.fastq > vertCatAnn/ej2v.ann.fastq
obiannotate -S 'sample:ej10v' vertCat/ej10v.fastq > vertCatAnn/ej10v.ann.fastq
obiannotate -S 'sample:ej40v' vertCat/ej40v.fastq > vertCatAnn/ej40v.ann.fastq
obiannotate -S 'sample:ej46v' vertCat/ej46v.fastq > vertCatAnn/ej46v.ann.fastq
obiannotate -S 'sample:ej51v' vertCat/ej51v.fastq > vertCatAnn/ej51v.ann.fastq
obiannotate -S 'sample:ej54v' vertCat/ej54v.fastq > vertCatAnn/ej54v.ann.fastq
obiannotate -S 'sample:fp4v' vertCat/fp4v.fastq > vertCatAnn/fp4v.ann.fastq
obiannotate -S 'sample:fp5v' vertCat/fp5v.fastq > vertCatAnn/fp5v.ann.fastq
obiannotate -S 'sample:fp7v' vertCat/fp7v.fastq > vertCatAnn/fp7v.ann.fastq
obiannotate -S 'sample:fp8v' vertCat/fp8v.fastq > vertCatAnn/fp8v.ann.fastq
obiannotate -S 'sample:fp9v' vertCat/fp9v.fastq > vertCatAnn/fp9v.ann.fastq
obiannotate -S 'sample:hs1v' vertCat/hs1v.fastq > vertCatAnn/hs1v.ann.fastq
obiannotate -S 'sample:hs2v' vertCat/hs2v.fastq > vertCatAnn/hs2v.ann.fastq
obiannotate -S 'sample:hs3v' vertCat/hs3v.fastq > vertCatAnn/hs3v.ann.fastq
obiannotate -S 'sample:hs4v' vertCat/hs4v.fastq > vertCatAnn/hs4v.ann.fastq
obiannotate -S 'sample:m249v' vertCat/m249v.fastq > vertCatAnn/m249v.ann.fastq
obiannotate -S 'sample:m570v' vertCat/m570v.fastq > vertCatAnn/m570v.ann.fastq
obiannotate -S 'sample:mrgp13v' vertCat/mrgp13v.fastq > vertCatAnn/mrgp13v.ann.fastq
obiannotate -S 'sample:mrgp323v' vertCat/mrgp323v.fastq > vertCatAnn/mrgp323v.ann.fastq
obiannotate -S 'sample:mrgp395v' vertCat/mrgp395v.fastq > vertCatAnn/mrgp395v.ann.fastq
obiannotate -S 'sample:mrgp399v' vertCat/mrgp399v.fastq > vertCatAnn/mrgp399v.ann.fastq
obiannotate -S 'sample:mrgp401v' vertCat/mrgp401v.fastq > vertCatAnn/mrgp401v.ann.fastq
obiannotate -S 'sample:mrgp414v' vertCat/mrgp414v.fastq > vertCatAnn/mrgp414v.ann.fastq
obiannotate -S 'sample:mrgp424v' vertCat/mrgp424v.fastq > vertCatAnn/mrgp424v.ann.fastq
obiannotate -S 'sample:mrgp564v' vertCat/mrgp564v.fastq > vertCatAnn/mrgp564v.ann.fastq
obiannotate -S 'sample:mrgp577v' vertCat/mrgp577v.fastq > vertCatAnn/mrgp577v.ann.fastq
obiannotate -S 'sample:nybg1v' vertCat/nybg1v.fastq > vertCatAnn/nybg1v.ann.fastq
obiannotate -S 'sample:nybg2v' vertCat/nybg2v.fastq > vertCatAnn/nybg2v.ann.fastq
obiannotate -S 'sample:nybg3v' vertCat/nybg3v.fastq > vertCatAnn/nybg3v.ann.fastq
obiannotate -S 'sample:nybg4v' vertCat/nybg4v.fastq > vertCatAnn/nybg4v.ann.fastq
obiannotate -S 'sample:nybg5v' vertCat/nybg5v.fastq > vertCatAnn/nybg5v.ann.fastq
obiannotate -S 'sample:nybg6v' vertCat/nybg6v.fastq > vertCatAnn/nybg6v.ann.fastq
obiannotate -S 'sample:pbp10v' vertCat/pbp10v.fastq > vertCatAnn/pbp10v.ann.fastq
obiannotate -S 'sample:pbp13v' vertCat/pbp13v.fastq > vertCatAnn/pbp13v.ann.fastq
obiannotate -S 'sample:pbp19v' vertCat/pbp19v.fastq > vertCatAnn/pbp19v.ann.fastq
obiannotate -S 'sample:pbp23v' vertCat/pbp23v.fastq > vertCatAnn/pbp23v.ann.fastq
obiannotate -S 'sample:pbp33v' vertCat/pbp33v.fastq > vertCatAnn/pbp33v.ann.fastq
obiannotate -S 'sample:pbp43v' vertCat/pbp43v.fastq > vertCatAnn/pbp43v.ann.fastq
obiannotate -S 'sample:pbp44v' vertCat/pbp44v.fastq > vertCatAnn/pbp44v.ann.fastq
obiannotate -S 'sample:pbp45v' vertCat/pbp45v.fastq > vertCatAnn/pbp45v.ann.fastq
obiannotate -S 'sample:pc1v' vertCat/pc1v.fastq > vertCatAnn/pc1v.ann.fastq
obiannotate -S 'sample:pc2v' vertCat/pc2v.fastq > vertCatAnn/pc2v.ann.fastq
obiannotate -S 'sample:pc3v' vertCat/pc3v.fastq > vertCatAnn/pc3v.ann.fastq
obiannotate -S 'sample:pc5v' vertCat/pc5v.fastq > vertCatAnn/pc5v.ann.fastq
obiannotate -S 'sample:pc6v' vertCat/pc6v.fastq > vertCatAnn/pc6v.ann.fastq
obiannotate -S 'sample:pc7v' vertCat/pc7v.fastq > vertCatAnn/pc7v.ann.fastq
obiannotate -S 'sample:pc9v' vertCat/pc9v.fastq > vertCatAnn/pc9v.ann.fastq
obiannotate -S 'sample:pc10v' vertCat/pc10v.fastq > vertCatAnn/pc10v.ann.fastq
obiannotate -S 'sample:pc11v' vertCat/pc11v.fastq > vertCatAnn/pc11v.ann.fastq
obiannotate -S 'sample:rd6v' vertCat/rd6v.fastq > vertCatAnn/rd6v.ann.fastq
obiannotate -S 'sample:rd8v' vertCat/rd8v.fastq > vertCatAnn/rd8v.ann.fastq
obiannotate -S 'sample:rd9v' vertCat/rd9v.fastq > vertCatAnn/rd9v.ann.fastq
obiannotate -S 'sample:sr3v' vertCat/sr3v.fastq > vertCatAnn/sr3v.ann.fastq
obiannotate -S 'sample:sr9v' vertCat/sr9v.fastq > vertCatAnn/sr9v.ann.fastq
obiannotate -S 'sample:vc1v' vertCat/vc1v.fastq > vertCatAnn/vc1v.ann.fastq
obiannotate -S 'sample:vc3v' vertCat/vc3v.fastq > vertCatAnn/vc3v.ann.fastq
obiannotate -S 'sample:vc6v' vertCat/vc6v.fastq > vertCatAnn/vc6v.ann.fastq
obiannotate -S 'sample:vc7v' vertCat/vc7v.fastq > vertCatAnn/vc7v.ann.fastq
obiannotate -S 'sample:vc10v' vertCat/vc10v.fastq > vertCatAnn/vc10v.ann.fastq
obiannotate -S 'sample:vc17v' vertCat/vc17v.fastq > vertCatAnn/vc17v.ann.fastq
obiannotate -S 'sample:vc20v' vertCat/vc20v.fastq > vertCatAnn/vc20v.ann.fastq
obiannotate -S 'sample:vc24v' vertCat/vc24v.fastq > vertCatAnn/vc24v.ann.fastq
obiannotate -S 'sample:vc25v' vertCat/vc25v.fastq > vertCatAnn/vc25v.ann.fastq
obiannotate -S 'sample:vc26v' vertCat/vc26v.fastq > vertCatAnn/vc26v.ann.fastq
obiannotate -S 'sample:vc29v' vertCat/vc29v.fastq > vertCatAnn/vc29v.ann.fastq
obiannotate -S 'sample:vncdec4' vertCat/vncdec4.fastq > vertCatAnn/vncdec4.ann.fastq
obiannotate -S 'sample:vncdec11' vertCat/vncdec11.fastq > vertCatAnn/vncdec11.ann.fastq
obiannotate -S 'sample:vncdec15' vertCat/vncdec15.fastq > vertCatAnn/vncdec15.ann.fastq
obiannotate -S 'sample:vncdec15' vertCat/vncdec27.fastq > vertCatAnn/vncdec15.ann.fastq
obiannotate -S 'sample:vncdec29' vertCat/vncdec29.fastq > vertCatAnn/vncdec29.ann.fastq
obiannotate -S 'sample:vncjan10' vertCat/vncjan10.fastq > vertCatAnn/vncjan10.ann.fastq
obiannotate -S 'sample:vpc' vertCat/vpc.fastq > vertCatAnn/vpc.ann.fastq
obiannotate -S 'sample:wpr78v' vertCat/wpr78v.fastq > vertCatAnn/wpr78v.ann.fastq