cutadapt -g TTAGATACCCCACTATGC -o BS1V.trimF.fastq BS1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o BS1V.trimFR.fastq BS1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o BP6V.trimF.fastq BP6V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o BP6V.trimFR.fastq BP6V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o CN1V.trimF.fastq CN1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o CN1V.trimFR.fastq CN1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o CN2V.trimF.fastq CN2V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o CN2V.trimFR.fastq CN2V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o CT1V.trimF.fastq CT1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o CT1V.trimFR.fastq CT1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o CT2V.trimF.fastq CT2V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o CT2V.trimFR.fastq CT2V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o CT3V.trimF.fastq CT3V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o CT3V.trimFR.fastq CT3V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o CT4V.trimF.fastq CT4V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o CT4V.trimFR.fastq CT4V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o CT5V.trimF.fastq CT5V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o CT5V.trimFR.fastq CT5V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ2V.trimF.fastq EJ2V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ2V.trimFR.fastq EJ2V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ10V.trimF.fastq EJ10V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ10V.trimFR.fastq EJ10V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ26V.trimF.fastq EJ26V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ26V.trimFR.fastq EJ26V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ29V.trimF.fastq EJ29V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ29V.trimFR.fastq EJ29V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ32V.trimF.fastq EJ32V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ32V.trimFR.fastq EJ32V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ34V.trimF.fastq EJ34V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ34V.trimFR.fastq EJ34V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ39V.trimF.fastq EJ39V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ39V.trimFR.fastq EJ39V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ40V.trimF.fastq EJ40V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ40V.trimFR.fastq EJ40V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ46V.trimF.fastq EJ46V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ46V.trimFR.fastq EJ46V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ51V.trimF.fastq EJ51V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ51V.trimFR.fastq EJ51V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o EJ54V.trimF.fastq EJ54V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o EJ54V.trimFR.fastq EJ54V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o FA1V.trimF.fastq FA1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o FA1V.trimFR.fastq FA1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o FA2V.trimF.fastq FA2V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o FA2V.trimFR.fastq FA2V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o FP4V.trimF.fastq FP4V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o FP4V.trimFR.fastq FP4V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o FP7V.trimF.fastq FP7V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o FP7V.trimFR.fastq FP7V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o FP8V.trimF.fastq FP8V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o FP8V.trimFR.fastq FP8V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o FP9V.trimF.fastq FP9V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o FP9V.trimFR.fastq FP9V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o FP15V.trimF.fastq FP15V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o FP15V.trimFR.fastq FP15V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o HP1V.trimF.fastq HP1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o HP1V.trimFR.fastq HP1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o HS1V.trimF.fastq HS1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o HS1V.trimFR.fastq HS1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o HS2V.trimF.fastq HS2V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o HS2V.trimFR.fastq HS2V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o HS3V.trimF.fastq HS3V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o HS3V.trimFR.fastq HS3V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o HS4V.trimF.fastq HS4V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o HS4V.trimFR.fastq HS4V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o HS5V.trimF.fastq HS5V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o HS5V.trimFR.fastq HS5V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o HS6V.trimF.fastq HS6V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o HS6V.trimFR.fastq HS6V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o HS7V.trimF.fastq HS7V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o HS7V.trimFR.fastq HS7V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o HS8V.trimF.fastq HS8V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o HS8V.trimFR.fastq HS8V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M13V.trimF.fastq M13V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M13V.trimFR.fastq M13V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M151V.trimF.fastq M151V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M151V.trimFR.fastq M151V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M174V.trimF.fastq M174V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M174V.trimFR.fastq M174V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M221V.trimF.fastq M221V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M221V.trimFR.fastq M221V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M232V.trimF.fastq M232V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M232V.trimFR.fastq M232V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M239V.trimF.fastq M239V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M239V.trimFR.fastq M239V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M241V.trimF.fastq M241V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M241V.trimFR.fastq M241V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M251V.trimF.fastq M251V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M251V.trimFR.fastq M251V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M320V.trimF.fastq M320V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M320V.trimFR.fastq M320V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M350V.trimF.fastq M350V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M350V.trimFR.fastq M350V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M395V.trimF.fastq M395V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M395V.trimFR.fastq M395V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M399V.trimF.fastq M399V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M399V.trimFR.fastq M399V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M401V.trimF.fastq M401V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M401V.trimFR.fastq M401V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M414V.trimF.fastq M414V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M414V.trimFR.fastq M414V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M422V.trimF.fastq M422V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M422V.trimFR.fastq M422V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M428V.trimF.fastq M428V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M428V.trimFR.fastq M428V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M570V.trimF.fastq M570V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M570V.trimFR.fastq M570V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o M577V.trimF.fastq M577V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o M577V.trimFR.fastq M577V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o NY1V.trimF.fastq NY1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o NY1V.trimFR.fastq NY1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o NY2V.trimF.fastq NY2V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o NY2V.trimFR.fastq NY2V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o NY3V.trimF.fastq NY3V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o NY3V.trimFR.fastq NY3V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o NY4V.trimF.fastq NY4V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o NY4V.trimFR.fastq NY4V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o NY5V.trimF.fastq NY5V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o NY5V.trimFR.fastq NY5V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o NY6V.trimF.fastq NY6V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o NY6V.trimFR.fastq NY6V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o NYBG8V.trimF.fastq NYBG8V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o NYBG8V.trimFR.fastq NYBG8V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o NYBG9V.trimF.fastq NYBG9V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o NYBG9V.trimFR.fastq NYBG9V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o NYBG10V.trimF.fastq NYBG10V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o NYBG10V.trimFR.fastq NYBG10V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP10V.trimF.fastq PBP10V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP10V.trimFR.fastq PBP10V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP13V.trimF.fastq PBP13V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP13V.trimFR.fastq PBP13V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP15V.trimF.fastq PBP15V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP15V.trimFR.fastq PBP15V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP19V.trimF.fastq PBP19V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP19V.trimFR.fastq PBP19V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP23V.trimF.fastq PBP23V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP23V.trimFR.fastq PBP23V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP27V.trimF.fastq PBP27V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP27V.trimFR.fastq PBP27V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP32V.trimF.fastq PBP32V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP32V.trimFR.fastq PBP32V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP33V.trimF.fastq PBP33V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP33V.trimFR.fastq PBP33V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP41V.trimF.fastq PBP41V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP41V.trimFR.fastq PBP41V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP42V.trimF.fastq PBP42V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP42V.trimFR.fastq PBP42V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PBP43V.trimF.fastq PBP43V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PBP43V.trimFR.fastq PBP43V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PC1V.trimF.fastq PC1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PC1V.trimFR.fastq PC1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PC2V.trimF.fastq PC2V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PC2V.trimFR.fastq PC2V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PC3V.trimF.fastq PC3V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PC3V.trimFR.fastq PC3V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PC5V.trimF.fastq PC5V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PC5V.trimFR.fastq PC5V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PC6V.trimF.fastq PC6V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PC6V.trimFR.fastq PC6V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PC7V.trimF.fastq PC7V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PC7V.trimFR.fastq PC7V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PC9V.trimF.fastq PC9V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PC9V.trimFR.fastq PC9V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PC10V.trimF.fastq PC10V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PC10V.trimFR.fastq PC10V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PC11V.trimF.fastq PC11V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PC11V.trimFR.fastq PC11V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PP1V.trimF.fastq PP1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PP1V.trimFR.fastq PP1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PP3V.trimF.fastq PP3V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PP3V.trimFR.fastq PP3V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PP7V.trimF.fastq PP7V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PP7V.trimFR.fastq PP7V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PP8V.trimF.fastq PP8V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PP8V.trimFR.fastq PP8V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o PP9V.trimF.fastq PP9V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o PP9V.trimFR.fastq PP9V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD2V.trimF.fastq RD2V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD2V.trimFR.fastq RD2V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD4V.trimF.fastq RD4V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD4V.trimFR.fastq RD4V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD5V.trimF.fastq RD5V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD5V.trimFR.fastq RD5V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD6V.trimF.fastq RD6V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD6V.trimFR.fastq RD6V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD8V.trimF.fastq RD8V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD8V.trimFR.fastq RD8V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD9V.trimF.fastq RD9V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD9V.trimFR.fastq RD9V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD10V.trimF.fastq RD10V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD10V.trimFR.fastq RD10V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD11V.trimF.fastq RD11V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD11V.trimFR.fastq RD11V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD12V.trimF.fastq RD12V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD12V.trimFR.fastq RD12V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD14V.trimF.fastq RD14V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD14V.trimFR.fastq RD14V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD15V.trimF.fastq RD15V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD15V.trimFR.fastq RD15V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD18V.trimF.fastq RD18V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD18V.trimFR.fastq RD18V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD23V.trimF.fastq RD23V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD23V.trimFR.fastq RD23V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD25V.trimF.fastq RD25V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD25V.trimFR.fastq RD25V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RD26V.trimF.fastq RD26V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RD26V.trimFR.fastq RD26V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RRP3V.trimF.fastq RRP3V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RRP3V.trimFR.fastq RRP3V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RRP4BV.trimF.fastq RRP4BV.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RRP4BV.trimFR.fastq RRP4BV.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RRP4V.trimF.fastq RRP4V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RRP4V.trimFR.fastq RRP4V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RRP5V.trimF.fastq RRP5V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RRP5V.trimFR.fastq RRP5V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o RRP6V.trimF.fastq RRP6V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o RRP6V.trimFR.fastq RRP6V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o SR3V.trimF.fastq SR3V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o SR3V.trimFR.fastq SR3V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o SR9V.trimF.fastq SR9V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o SR9V.trimFR.fastq SR9V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o SR11V.trimF.fastq SR11V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o SR11V.trimFR.fastq SR11V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o SR19V.trimF.fastq SR19V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o SR19V.trimFR.fastq SR19V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o SR24V.trimF.fastq SR24V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o SR24V.trimFR.fastq SR24V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o SR29V.trimF.fastq SR29V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o SR29V.trimFR.fastq SR29V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o ST3V.trimF.fastq ST3V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o ST3V.trimFR.fastq ST3V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o ST4V.trimF.fastq ST4V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o ST4V.trimFR.fastq ST4V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o ST5V.trimF.fastq ST5V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o ST5V.trimFR.fastq ST5V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o ST12V.trimF.fastq ST12V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o ST12V.trimFR.fastq ST12V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o SV5V.trimF.fastq SV5V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o SV5V.trimFR.fastq SV5V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC1V.trimF.fastq VC1V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC1V.trimFR.fastq VC1V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC3V.trimF.fastq VC3V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC3V.trimFR.fastq VC3V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC6V.trimF.fastq VC6V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC6V.trimFR.fastq VC6V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC7V.trimF.fastq VC7V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC7V.trimFR.fastq VC7V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC10V.trimF.fastq VC10V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC10V.trimFR.fastq VC10V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC12V.trimF.fastq VC12V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC12V.trimFR.fastq VC12V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC17V.trimF.fastq VC17V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC17V.trimFR.fastq VC17V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC20V.trimF.fastq VC20V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC20V.trimFR.fastq VC20V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC23V.trimF.fastq VC23V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC23V.trimFR.fastq VC23V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC24V.trimF.fastq VC24V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC24V.trimFR.fastq VC24V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC25V.trimF.fastq VC25V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC25V.trimFR.fastq VC25V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC26V.trimF.fastq VC26V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC26V.trimFR.fastq VC26V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC29V.trimF.fastq VC29V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC29V.trimFR.fastq VC29V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VC38V.trimF.fastq VC38V.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VC38V.trimFR.fastq VC38V.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VNC_APR22.trimF.fastq VNC_APR22.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VNC_APR22.trimFR.fastq VNC_APR22.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VNC_JUN1.trimF.fastq VNC_JUN1.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VNC_JUN1.trimFR.fastq VNC_JUN1.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VNC_JUN3.trimF.fastq VNC_JUN3.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VNC_JUN3.trimFR.fastq VNC_JUN3.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VNC_JUN6.trimF.fastq VNC_JUN6.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VNC_JUN6.trimFR.fastq VNC_JUN6.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VNC_JUN9.trimF.fastq VNC_JUN9.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VNC_JUN9.trimFR.fastq VNC_JUN9.trimF.fastq
cutadapt -g TTAGATACCCCACTATGC -o VPOS.trimF.fastq VPOS.fastq
cutadapt -a CTAGAGGAGCCTGTTCTA -o VPOS.trimFR.fastq VPOS.trimF.fastq